apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: DaemonSet 
metadata:
  name: nginx-daemonset
spec:
  selector:
    matchLabels:
      app: nginx-ds
  template:
    metadata:
      labels:
        app: nginx-ds
    spec:
      containers:
      - name: nginx-ds
        image: nginx:1.7.9
        ports:
        - containerPort: 80

