apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginxservice
  name: nginxservice
spec:
  ports:
    # The port that this service should service on
    #     - port: 30080
    #       # Label keys and values that must match in order to receive traffic for this service
    #         selector:
    #             app: nginx
    #               type: LoadBalancer
    #
